### DISCUSSION TITLE
Error qmc5883l.sensor is marked FAILED

### DISCUSSION THREAD

**Discussion by sorz2122** [tronikos/esphome-magnetometer-water-gas-meter#12] [General]
I installed your version of the QMC8553L sensor but get the error: Communication with QMC5883L failed!
Component qmc5883l.sensor is marked FAILED

If I create a completely new project and just flash the following variables in ESPHome, I get a response from the sensor.

i2c:
  sda: GPIO4 # D2 corresponds to GPIO4 on the NodeMCU v2
  scl: GPIO5 # D1 corresponds to GPIO5 on the NodeMCU v2
  scan: True
  id: bus_a

sensor:
  - platform: qmc5883l
    address: 0x0D
    oversampling: 64x # 512x (default), 256x, 128x, 64x
    range: 800uT # 200uT, 800uT

Do you have an idea why it doesn't work for me?

**Comment by tronikos** [comment]
what's your config?

**Comment by sorz2122** [comment]
esphome:
  name: wasser
  friendly_name: Wasser

esp8266:
  board: nodemcuv2
  restore_from_flash: true

preferences:
  flash_write_interval: 60min

substitutions:
  #For water one of: CCF, ft³, gal, L, m³
  #For gas one of: CCF, ft³, m³
  volume_unit: 'L'
  i2c_scl: GPIO5  #D1
  i2c_sda: GPIO4  #D2

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    # Or for gas meter:
    # file: esphome-gas-meter.yaml
    # Or if you are using HMC5883L instead of QMC5883L:
    #files: [esphome-water-meter.yaml, hmc5883l.yaml]
    refresh: 0s

#Enable logging
logger:

#Enable Home Assistant API
api:

ota:

wifi:
  ssid: xxxx
  password: xxxx

**Comment by tronikos** [comment]
Seems fine. Try adding the following at the end of your config:

```yaml
i2c:
  - id: !extend ${prefix_id}i2c_bus
    scan: True
```

**Reply by sorz2122** [reply]
My new log: 
[17:17:15][I][app:100]: ESPHome version 2024.5.4 compiled on May 28 2024, 13:51:56
[17:17:15][C][wifi:580]: WiFi:
[17:17:15][C][wifi:408]:   Local MAC: 1XXXXXXXXXXX
[17:17:15][C][wifi:413]:   SSID: [redacted]
[17:17:15][C][wifi:416]:   IP Address: 192.168.178.63
[17:17:15][C][wifi:419]:   BSSID: [redacted]
[17:17:15][C][wifi:421]:   Hostname: 'wasser'
[17:17:15][C][wifi:423]:   Signal strength: -72 dB ▂▄▆█
[17:17:15][C][wifi:427]:   Channel: 1
[17:17:15][C][wifi:428]:   Subnet: 255.255.255.0
[17:17:15][C][wifi:429]:   Gateway: 192.168.178.1
[17:17:15][C][wifi:430]:   DNS1: 192.168.178.1
[17:17:15][C][wifi:431]:   DNS2: 0.0.0.0
[17:17:15][C][logger:185]: Logger:
[17:17:15][C][logger:186]:   Level: DEBUG
[17:17:15][C][logger:188]:   Log Baud Rate: 115200
[17:17:15][C][logger:189]:   Hardware UART: UART0
[17:17:15][C][logger:193]:   Level for 'qmc5883l': INFO
[17:17:15][C][i2c.arduino:071]: I2C Bus:
[17:17:15][C][i2c.arduino:072]:   SDA Pin: GPIO4
[17:17:15][C][i2c.arduino:073]:   SCL Pin: GPIO5
[17:17:15][C][i2c.arduino:074]:   Frequency: 50000 Hz
[17:17:15][C][i2c.arduino:086]:   Recovery: bus successfully recovered
[17:17:15][I][i2c.arduino:096]: Results from i2c bus scan:
[17:17:15][I][i2c.arduino:102]: Found i2c device at address 0x0D
[17:17:15][C][template.number:050]: Template Number 'Volume per half rotation'
[17:17:15][C][template.number:050]:   Unit of Measurement: 'L'
[17:17:15][C][template.number:051]:   Optimistic: YES
[17:17:15][C][template.number:052]:   Update Interval: never
[17:17:15][C][template.number:050]: Template Number 'Temperature Offset'
[17:17:15][C][template.number:050]:   Icon: 'mdi:thermometer'
[17:17:15][C][template.number:050]:   Unit of Measurement: '°C'
[17:17:15][C][template.number:051]:   Optimistic: YES
[17:17:15][C][template.number:052]:   Update Interval: never
[17:17:15][C][template.number:050]: Template Number 'Threshold lower'
[17:17:15][C][template.number:050]:   Unit of Measurement: 'µT'
[17:17:15][C][template.number:051]:   Optimistic: YES
[17:17:15][C][template.number:052]:   Update Interval: never
[17:17:15][C][template.number:050]: Template Number 'Threshold upper'
[17:17:15][C][template.number:050]:   Unit of Measurement: 'µT'
[17:17:15][C][template.number:051]:   Optimistic: YES
[17:17:15][C][template.number:052]:   Update Interval: never
[17:17:15][C][template.number:050]: Template Number 'Calibration time'
[17:17:15][C][template.number:050]:   Icon: 'mdi:timer'
[17:17:15][C][template.number:050]:   Unit of Measurement: 's'
[17:17:15][C][template.number:051]:   Optimistic: YES
[17:17:15][C][template.number:052]:   Update Interval: never
[17:17:15][C][template.select:065]: Template Select 'Axis'
[17:17:15][C][template.select:066]:   Update Interval: never
[17:17:15][C][template.select:069]:   Optimistic: YES
[17:17:15][C][template.select:070]:   Initial Option: None
[17:17:15][C][template.select:071]:   Restore Value: YES
[17:17:15][C][template.sensor:022]: Template Sensor 'Half rotations total'
[17:17:15][C][template.sensor:022]:   State Class: 'total_increasing'
[17:17:15][C][template.sensor:022]:   Unit of Measurement: ''
[17:17:15][C][template.sensor:022]:   Accuracy Decimals: 0
[17:17:15][C][template.sensor:022]:   Icon: 'mdi:counter'
[17:17:15][C][template.sensor:023]:   Update Interval: 1.0s
[17:17:15][C][template.sensor:022]: Template Sensor 'Total'
[17:17:15][C][template.sensor:022]:   Device Class: 'water'
[17:17:15][C][template.sensor:022]:   State Class: 'total_increasing'
[17:17:15][C][template.sensor:022]:   Unit of Measurement: 'L'
[17:17:15][C][template.sensor:022]:   Accuracy Decimals: 2
[17:17:15][C][template.sensor:022]:   Icon: 'mdi:water'
[17:17:15][C][template.sensor:023]:   Update Interval: 10.0s
[17:17:15][C][template.sensor:022]: Template Sensor 'Flow'
[17:17:15][C][template.sensor:022]:   State Class: 'measurement'
[17:17:15][C][template.sensor:022]:   Unit of Measurement: 'L/min'
[17:17:15][C][template.sensor:022]:   Accuracy Decimals: 2
[17:17:15][C][template.sensor:023]:   Update Interval: 10.0s
[17:17:15][C][switch.gpio:068]: GPIO Switch 'led'
[17:17:15][C][switch.gpio:090]:   Restore Mode: always OFF
[17:17:15][C][switch.gpio:031]:   Pin: GPIO2
[17:17:15][C][template.sensor:022]: Template Sensor 'axis_value'
[17:17:15][C][template.sensor:022]:   State Class: ''
[17:17:15][C][template.sensor:022]:   Unit of Measurement: ''
[17:17:15][C][template.sensor:022]:   Accuracy Decimals: 1
[17:17:15][C][template.sensor:023]:   Update Interval: 60.0s
[17:17:15][C][mdns:115]: mDNS:
[17:17:15][C][mdns:116]:   Hostname: wasser
[17:17:15][C][ota:096]: Over-The-Air Updates:
[17:17:15][C][ota:097]:   Address: wasser.local:8266
[17:17:15][C][ota:103]:   OTA version: 2.
[17:17:15][C][api:139]: API Server:
[17:17:15][C][api:140]:   Address: wasser.local:6053
[17:17:15][C][api:144]:   Using noise encryption: NO
[17:17:19][D][sensor:093]: 'Flow': Sending state 0.00000 L/min with 2 decimals of accuracy
[17:17:39][D][button:010]: 'Calibrate axis' Pressed.
[17:17:39][I][calibration:184]: Starting calibration. Make sure water is running
[17:17:44][I][calibration:201]: x ranged from 0.00 to 0.00
[17:17:44][I][calibration:207]: y ranged from 0.00 to 0.00
[17:17:44][I][calibration:213]: z ranged from 0.00 to 0.00
[17:17:44][E][calibration:231]: Calibration failed. No axis had a range of at least 20
[17:18:09][D][sensor:093]: 'Total': Sending state 0.00000 L with 2 decimals of accuracy
[17:18:29][D][sensor:093]: 'Flow': Sending state 0.00000 L/min with 2 decimals of accuracy



Apparently the sensor is connected, it also gives me a temperature value, but when I calibrate it, I get no values from the sensor. 

I bought this one:  https://www.amazon.de/dp/B07P99HFHS?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Reply by sorz2122** [reply]
[17:17:39][D][button:010]: 'Calibrate axis' Pressed.
[17:17:39][I][calibration:184]: Starting calibration. Make sure water is running
**[17:17:44][I][calibration:201]: x ranged from 0.00 to 0.00
[17:17:44][I][calibration:207]: y ranged from 0.00 to 0.00
[17:17:44][I][calibration:213]: z ranged from 0.00 to 0.00**
**[17:17:44][E][calibration:231]: Calibration failed. No axis had a range of at least 20**
[17:18:09][D][sensor:093]: 'Total': Sending state 0.00000 L with 2 decimals of accuracy
[17:18:29][D][sensor:093]: 'Flow': Sending state 0.00000 L/min with 2 decimals of accuracy
[17:19:19][D][sensor:093]: 'Total': Sending state 0.00000 L with 2 decimals of accuracy
[17:19:29][D][sensor:093]: 'Flow': Sending state 0.00000 L/min with 2 decimals of accuracy
[17:20:06][D][sensor:093]: 'Temperature': Sending state 33.00000 °C with 1 decimals of accuracy
[17:20:29][D][sensor:093]: 'Total': Sending state 0.00000 L with 2 decimals of accuracy
[17:20:29][D][sensor:093]: 'Flow': Sending state 0.00000 L/min with 2 decimals of accuracy
[17:21:29][D][sensor:093]: 'Flow': Sending state 0.00000 L/min with 2 decimals of accuracy
[17:21:39][D][sensor:093]: 'Total': Sending state 0.00000 L with 2 decimals of accuracy
[17:22:01][D][ota:154]: Starting OTA Update from 192.168.178.43...
[17:22:01][W][component:157]: Component ota set Warning flag: unspecified
**[17:22:01][W][ota:166]: Magic bytes do not match! 0x47-0x45-0x54-0x20-0x2F**
[17:22:01][E][component:164]: Component ota set Error flag: unspecified
[17:22:02][D][ota:154]: Starting OTA Update from 192.168.178.43...
[17:22:02][W][ota:166]: Magic bytes do not match! 0x47-0x45-0x54-0x20-0x2F
[17:22:02][W][component:237]: Component ota took a long time for an operation (235 ms).
[17:22:02][W][component:238]: Components should block for at most 30 ms.

**Reply by tronikos** [reply]
What if you also add the following?

```yaml
sensor:
  - id: !extend ${prefix_id}qmc5883l_id
    range: 800uT
```

**Reply by sorz2122** [reply]
Apparently a ground pole on my ESP is defective. Now the sensor also works with the standard code. However, the calibration doesn't work. 

[15:03:08][D][button:010]: 'Calibrate axis' Pressed.
[15:03:08][I][calibration:184]: Starting calibration. Make sure water is running
[15:03:11][D][sensor:093]: 'Magnetic Field Strength X': Sending state -3.18206 µT with 1 decimals of accuracy
[15:03:11][D][sensor:093]: 'Magnetic Field Strength X': Sending state 0.18326 µT with 1 decimals of accuracy
[15:03:13][D][sensor:093]: 'Magnetic Field Strength X': Sending state -3.05711 µT with 1 decimals of accuracy
[15:03:13][D][sensor:093]: 'Magnetic Field Strength X': Sending state 0.39151 µT with 1 decimals of accuracy
[15:03:14][D][sensor:093]: 'Magnetic Field Strength X': Sending state -2.97381 µT with 1 decimals of accuracy
[15:03:14][D][sensor:093]: 'Magnetic Field Strength X': Sending state 0.39151 µT with 1 decimals of accuracy
[15:03:18][I][calibration:201]: x ranged from -3.18 to 1.56
[15:03:18][I][calibration:207]: y ranged from -1.62 to 1.75
[15:03:18][I][calibration:213]: z ranged from -2.02 to 1.93
**[15:03:18][E][calibration:231]: Calibration failed. No axis had a range of at least 20**

![image](https://github.com/tronikos/esphome-magnetometer-water-gas-meter/assets/81297488/7509c4df-0762-4da9-ba85-0969423c2211)

**Reply by tronikos** [reply]
I think you need to find a better spot on the meter to get better values. You can manually calibrate it but I'm not sure how accurate it will be if the variation is so small.

**Comment by erwyman** [comment]
I too am getting this error message. Any assistance is greatly appreciated. Using a TinyS3 (ESP32S3) and QMC5883L. VCC to 5V, GND to GND, SCL to D1 and SDA to D2. Below is my config:

```
substitutions:
  # For water one of: CCF, ft³, gal, L, m³
  # For gas one of: CCF, ft³, m³
  volume_unit: 'ft³'
  i2c_scl: GPIO5  # D1
  i2c_sda: GPIO4  # D2
  # Set to false only if needed during manual calibration.
  # Do not keep them at false since these slow down the ESP device
  # and reduce the accuracy during high flow.
  hide_magnetic_field_strength_sensors: 'true'
  hide_half_rotations_total_sensor: 'true'

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    # file: esphome-water-meter.yaml
    # Or for gas meter:
    file: esphome-gas-meter.yaml
    # Or if you are using HMC5883L instead of QMC5883L:
    # files: [esphome-water-meter.yaml, hmc5883l.yaml]
    refresh: 0s

i2c:
  - id: !extend ${prefix_id}i2c_bus
    scan: True

sensor:
  - id: !extend ${prefix_id}qmc5883l_id
    range: 800uT

esphome:
  name: redacted
  friendly_name: Natural Gas Meter Sensor

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  - platform: esphome
    password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  reboot_timeout: 15min
  ap:
    ssid: "redacted"
    password: "redacted"
  power_save_mode: none
  enable_on_boot: True
  fast_connect: On
  output_power: 8.5

captive_portal:
```

**Reply by erwyman** [reply]
I just read in an Arduino forum that thr QMC5883L is a 3.3v device and connecting it to 5v could fry the board. I tired moving it to the 3.3v header on the TinyS3 and am getting the same result. Is this likely this is the issue?

**Reply by erwyman** [reply]
I believe I have solved the issue. It seems the pinout may be different, or maybe it just confused me... pretty new to all of this. On the TinyS3, the card shows D1 on IO1 and D2 on IO2. I moved the headers to IO5 and IO4 and it appears to be loading without error. VCC is still on 3.3v.

Originally I tried changing the code to have SCL on GPIO1 and SDA on GPIO2 but got an error that GPIO2 was already in use in another file in the package. It appears to be for controlling an LED. The LED's for this board are RGB LED DATA IO18 and RGB LED PWR IO17. I'm wondering if this means the LED won't work for whatever the LED was supposed to be doing... But I don't know enough about these to try and tackle changing it.

**Comment by CamMakoJ** [comment]
I'm having a similiar problem, im using an ESP32-C6-devkit and it just seems to not want to connect i did an I2C scan in arduino and it found the device at the expected address; i have SCA on pin 7 and SCL on pin 6. It won't provide any data back from the QMC (its label HMC5887L - GY-273). I have it run to 3.3v, ground, and pin 6 (SCA) and 7 (SCL)

**Reply by CamMakoJ** [reply]
To provide more context - i have tried a ton of config variations but I'm still learning some of the nuance of ESPhome (and ESP32 in general). The error i get is:
[10:08:27][C][qmc5883l:069]: QMC5883L:
[10:08:27][C][qmc5883l:070]:   Address: 0x0D
[10:08:27][E][qmc5883l:072]: Communication with QMC5883L failed!

my config is:

is the standard which failed, but i have also add the i2c: 

substitutions:
  volume_unit: 'L'
  i2c_scl: GPIO6
  i2c_sda: GPIO7
  hide_magnetic_field_strength_sensors: 'false'
  hide_half_rotations_total_sensor: 'false'

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    refresh: 0s

**Reply by CamMakoJ** [reply]
Ok so i have legit been messing with this for a week... and for some reason.... it now works....

**Comment by rugene76** [comment]
I too am having a "Communication with QMC5883L failed!" issue
I'm using an esp32-s3-devkitc-1, with SCL on gpio5 and sda on GPIO4, I also tried 8 and 9
For test purposes, I'm using an 8 inch cable. Later, I'm hoping to use a cat6a 30ft cable.

The code is as provided for this project to provide a good starting point.

In the log I get:
[16:19:28][I][i2c.arduino:096]: Results from i2c bus scan:
[16:19:28][I][i2c.arduino:102]: Found i2c device at address 0x2C
[16:19:28][E][qmc5883l:072]: Communication with QMC5883L failed!
[16:19:28][E][component:085]:   Component qmc5883l.sensor is marked FAILED:

So it appears the device is found but has somehow failed.
I've tried 2 different devices and 3.3v and 5v with no luck.

I bought the devices from Amazon, https://www.amazon.com/dp/B0CFLPKTP1?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

I am stuck :-{

any ideas?

thanks much

**Reply by rugene76** [reply]
and I also tried a plain esp32 -wroom-32 with the same result.....

**Reply by Anathema-Device** [reply]
I see in the esphome-magnetometer.yaml code that it has:
```
  - platform: qmc5883l
    id: ${prefix_id}qmc5883l_id
    i2c_id: ${prefix_id}i2c_bus
    address: 0x0D
```
and you show
`[16:19:28][I][i2c.arduino:102]: Found i2c device at address 0x2C`
so maybe the device address in the code for you needs to be changed?

**Reply by rugene76** [reply]
thanks so much for looking at this. 
Yes, I realized the same. I moved the files locally and modified the address. I'm not sure how to automatically update the address so I just changed it in the code.

Things seem to be working now. Next up is to attach the sensor to my water meter and see what happens.

btw, I'm replacing my flume device that has now failed twice in 3 years.

If all goes well, I plan to design a 3d printable box with RJ45 connectors to connect to and read both my water and gas meters.

**Reply by tronikos** [reply]
You can add the following at the end of your config that includes the package in this repo:
```
sensor:
  - platform: qmc5883l
    id: !extend ${prefix_id}qmc5883l_id
    address: 0x2C
```
