### DISCUSSION TITLE
Calibration not saving after power cycle of ESP

### DISCUSSION THREAD

**Discussion by mickcomp** [tronikos/esphome-magnetometer-water-gas-meter#24] [General]
I have this setup for reading my gas meter, works well!  I have noticed that if i power cycle my esp it looses all the calibration settings and goes back to defaults.  not sure how to make the settings stay

**Comment by tronikos** [comment]
What ESP device do you have? Can you post your config?

**Comment by mickcomp** [comment]
its just a mini d like the one you have

```yaml
esphome:
  name: gas-meter-reader
  friendly_name: Gas Meter Reader

esp8266:
  board: esp01_1m

# Enable logging
logger:

preferences:
  flash_write_interval: 60min

# Enable Home Assistant API
api:
  encryption:
    key: "aGp/jQSnFu8ajEv2Fg/vQA+VcSz50Or9ktZsjXEvCsM="

ota:
  - platform: esphome
    password: "dee2a1b2a1b0a09e761954ad83245ddc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Meter-Reader Fallback Hotspot"
    password: "hxuFKCWxhrH0"


substitutions:
  # For water one of: CCF, ft³, gal, L, m³
  # For gas one of: CCF, ft³, m³
  volume_unit: 'm³'
  i2c_scl: GPIO5  # D1
  i2c_sda: GPIO4  # D2

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-gas-meter.yaml
    # Or for gas meter:
    # file: esphome-gas-meter.yaml
    # Or if you are using HMC5883L instead of QMC5883L:
    # files: [esphome-water-meter.yaml, hmc5883l.yaml]
    refresh: 0s        

captive_portal:
```

**Reply by tronikos** [reply]
You missed step 5:

Skip this step if you used an esp32. Change esp8266 section to:

```yaml
esp8266:
  board: d1_mini
  restore_from_flash: true

preferences:
  flash_write_interval: 60min
```

specifically the `restore_from_flash: true` line
