### DISCUSSION TITLE
How change LED output?

### DISCUSSION THREAD

**Discussion by 7lano** [tronikos/esphome-magnetometer-water-gas-meter#30] [Q&A] [answered]
Hello!
In esphome-water-meter.yaml file is LED configuration.
I need to change LED from GPIO2 to GPIO33 or GPIO4
Is there any option to overwrite this setting to my own?

**Comment by tronikos** [comment, marked as answer]
I'll add a substitution to make it easier. 
In the meantime, add something like the following at the end of your config: 

```
switch:
  - id: !extend led
    pin:
      number: GPIO4
```
