### DISCUSSION TITLE
How to update our local install of this repository

### DISCUSSION THREAD

**Discussion by JAudi23** [tronikos/esphome-magnetometer-water-gas-meter#5] [General]
Hello, apologies if this has an obvious answer, but this is the first time I've used a GitHub repository that had a "package" URL embedded as part of the code.

```yml
packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    # Or for gas meter:
    # file: esphome-gas-meter.yaml
    refresh: 0s
```

How do we make sure our install is getting all of the updates that are being made to the packages?  Is it as simple as updating the ``refresh`` variable to a set number of seconds?

Thanks,
