### DISCUSSION TITLE
Erroneous Initial Temperature Reading After ESP32 Reboot

### DISCUSSION THREAD

**Discussion by bluecrystaldex** [tronikos/esphome-magnetometer-water-gas-meter#51] [Q&A] [answered]
My QMC5883L returns an erroneous (high) initial temperature reading that I'd like to filter out, but I'm not sure how to append another sensor filter into the config without making all config files local. I'd like to add `- skip_initial: 1` to the filters section of the temperature sensor config in esphome-magnetometer.yaml. Based on the [ESPHome documentation](https://esphome.io/components/packages.html#extend) it looks like this should be possible, but I'm not sure how to get the syntax correct with the nested file structure of the GitHub package.

This is the section of esphome-magnetometer.yaml I'm trying to "extend:"

    temperature:
      id: ${prefix_id}qmc5883l_temperature
      name: ${prefix_name}Temperature
      filters:
        - lambda: "return x + id(${prefix_id}temperature_offset).state;"
        - sliding_window_moving_average:
            window_size: 3000
            send_every: 3000
        - or:
            - throttle: 300s
            - delta: 0.5

**Comment by tronikos** [comment, marked as answer]
Does this work?

```yaml
sensor:
  - id: !extend ${prefix_id}qmc5883l_id
    temperature:
      filters:
        - skip_initial: 1
```

**Reply by bluecrystaldex** [reply]
I started to reply "no, that made the temperature sensor 'unknown'," but then I double checked the validation in ESPHome and saw this was the resulting filter section after your addition:

```
filters:
    - lambda: !lambda |-
        return x + id(temperature_offset).state;
    - sliding_window_moving_average:
        window_size: 3000
        send_every: 3000
        send_first_at: 1
    - or:
      - throttle: 300s
      - delta:
          value: 0.5
          type: absolute
    - skip_initial: 1
```

So your code added exactly what I wanted. Went back to look at the sensor value in HA a few seconds later and was pleasantly surprised to see a perfectly normal reading there. To be completely honest with you, my first thought was to write exactly the same bit of code you did, but I overthought it and assumed that would overwrite the `filter:` section entirely, not just append that one line. Thanks for the help! Love this integration.
