### DISCUSSION TITLE
Gas Meter total is in L when configured for m³ and m³ is expected by HA Energy config

### DISCUSSION THREAD

**Discussion by Anathema-Device** [tronikos/esphome-magnetometer-water-gas-meter#60] [General]
Trying to add the gas meter values to HA's Energy page it complains about the units being L instead of m³.  What do I need to change to make the  Gasmeter Total (sensor.gasmeter_total) to show in m³?  This is what I have for the ESP:

```
substitutions:
  volume_unit: 'm³'
  i2c_scl: GPIO5  # D1
  i2c_sda: GPIO4  # D2
  # Set to false only if needed during manual calibration.
  # Do not keep them at false since these slow down the ESP device
  # and reduce the accuracy during high flow.
  hide_magnetic_field_strength_sensors: 'false' # 'true'
  hide_half_rotations_total_sensor: 'false' # 'true'

switch:
  - id: !extend led
    pin:
      number: GPIO3

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    # file: esphome-water-meter.yaml
    # Or for gas meter:
    file: esphome-gas-meter.yaml
    refresh: 0s
```  
Thanks!
