### DISCUSSION TITLE
Dual meters on 1 Esp8266?

### DISCUSSION THREAD

**Discussion by steve3j** [tronikos/esphome-magnetometer-water-gas-meter#61] [General]
Using Pins 12/14 and 4/5. Does dual meters work on ESP8266 or only on a ESP32? Keep getting an error:

[23:09:12][E][qmc5883l:072]: Communication with QMC5883L failed!
[23:09:12][E][component:082]:   Component qmc5883l.sensor is marked FAILED

**Comment by tronikos** [comment]
The esphome-two-meters.yaml config is untested. See #34 for a previous report of not working. Unfortunately I have no way of testing and fixing this. 

Without doing any wiring changes, I recommend trying the following config to confirm you can read the magnetometer connected to 4/5:

```yaml
substitutions:
  volume_unit: 'gal'
  i2c_scl: GPIO5
  i2c_sda: GPIO4

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    refresh: 0s
```

and then trying the following to confirm you can read the magnetometer connected to 12/14:

```yaml
substitutions:
  volume_unit: 'gal'
  i2c_scl: GPIO14
  i2c_sda: GPIO12

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    refresh: 0s
```

**Comment by steve3j** [comment]
Wasn't seeing my external gas sensor on i2c. Reworked my ethernet grounding and resoldered a few things.
Got it to work sort of. I can see data from both now.
But the D1Mini seems to reset about every 30 seconds. Not sure why this would be.
Works fine if configured for either one(but not both) of the attached sensors.

Edit: seems to reset maybe 20 times, then is no longer available in home assistant. Then randomly it'll come back. Pushing calibrate axis seems to exacerbate the issue and cause a reset sometimes. When it doesn't cause a reset, it seems to do nothing.


My current config.

```yaml
esphome:
  name: esphome-web-6e48ff
  friendly_name: Dual Meter ESP8266
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp8266:
  board: d1_mini
  restore_from_flash: true

preferences:
  flash_write_interval: 5min

#Enable logging
logger:

#Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  #Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dual-meter Fallback Hotspot"
    password: !secret wifi_password

#Allow Over-The-Air updates
ota:
- platform: esphome

captive_portal:

substitutions:
  volume_unit1: 'ft³'
  volume_unit2: 'gal'
  i2c1_scl: D1
  i2c1_sda: D2
  i2c2_scl: D5
  i2c2_sda: D6
  #hide_magnetic_field_strength_sensors: 'false'
  #hide_half_rotations_total_sensor: 'false'

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    #file: esphome-water-meter.yaml
    file: esphome-two-meters.yaml
    refresh: 0s

#i2c1:
#  #- id: !extend ${prefix_id}i2c_bus
#    #scan: True

#i2c2:
#  #- id: !extend ${prefix_id}i2c_bus
#    #scan: True
```
