### DISCUSSION TITLE
sensor.water_meter vs sensor.water_meter_total

### DISCUSSION THREAD

**Discussion by talormanda** [tronikos/esphome-magnetometer-water-gas-meter#62] [Q&A]
Been running this for a few months. Confused by this.

After I created everything, there is:

sensor.water_meter
and
sensor.water_meter_total

what is the _total sensor and why does it exist? Currently both sensors are "gal" and the numbers are a little bit off from each other.

sensor.water_meter is 30359.17 and sensor.water_meter_total is 30777.66

the usage between two points in time seems to be the same. for example, if i look at a 3 hour period and subtract the difference, both sensors say the same amount of gallons is used. so what is the point of _total? it doesnt look like anything I created because I cant remove it.

**Comment by tronikos** [comment]
I only have `sensor.water_meter_total`.
Can you remove the device and add it again? Go to http://homeassistant.local:8123/config/integrations/integration/esphome 3 dots on water meter -> delete. Then restart Home Assistant to automatically detect the device.
What's your config?

**Reply by talormanda** [reply]
My setup matches your picture though on this projects code page:
![image](https://github.com/user-attachments/assets/50eb4718-02fe-4c0f-8c5f-2522fcd046e4)

I have the main one, flow, temp, and total:
![image](https://github.com/user-attachments/assets/b0c08379-a5a0-4836-beef-c9b5fae92c1d)

Ignore the crossed off stuff. Those are helpers I linked to the sensor page.

They are: `sensor.water_meter` , `sensor.water_meter_flow` , `sensor.water_meter_temperature` , `sensor.water_meter_total` - these were all created by the device when I added it.

```
esphome:
  name: water-meter
  friendly_name: Water meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hidden"

ota:
  - platform: esphome
    password: "hidden"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.21
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.254.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Meter Fallback Hotspot"
    password: "hidden"

captive_portal:

substitutions:
  # For water one of: CCF, ft³, gal, L, m³
  # For gas one of: CCF, ft³, m³
  volume_unit: 'gal'
  i2c_scl: GPIO21  # D1
  i2c_sda: GPIO25  # D2
  # Set to false only if needed during manual calibration.
  # Do not keep them at false since these slow down the ESP device
  # and reduce the accuracy during high flow.
  hide_magnetic_field_strength_sensors: 'false'
  hide_half_rotations_total_sensor: 'false'

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    file: esphome-water-meter.yaml
    # Or for gas meter:
    # file: esphome-gas-meter.yaml
    # Or if you are using HMC5883L instead of QMC5883L:
    # files: [esphome-water-meter.yaml, hmc5883l.yaml]
    refresh: 0s    
```
