### DISCUSSION TITLE
Communication with HMC5883L failed!

### DISCUSSION THREAD

**Discussion by gmow1** [tronikos/esphome-magnetometer-water-gas-meter#66] [General]
Keep getting this error? I've tried 2 HMC sensors and same error. I've removed password etc from the pasted code.

Any suggestions?

```yaml
esphome:
  name: water-meter
  friendly_name: Water_Meter

esp8266:
  # board: esp01_1m
  board: d1_mini
  restore_from_flash: true

preferences:
  flash_write_interval: 60min

# Enable logging
logger:



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password





captive_portal:

substitutions:
  volume_unit: 'm³'
  i2c_scl: GPIO5  # D1
  i2c_sda: GPIO4  # D2
  # Set to false only if needed during manual calibration.
  # Do not keep them at false since these slow down the ESP device
  # and reduce the accuracy during high flow.
  hide_magnetic_field_strength_sensors: 'true'
  hide_half_rotations_total_sensor: 'true'

packages:
  meter:
    url: https://github.com/tronikos/esphome-magnetometer-water-gas-meter
    ref: main
    files: [esphome-water-meter.yaml, hmc5883l.yaml]
    # Or for gas meter:
    # file: esphome-gas-meter.yaml
    # Or if you are using HMC5883L instead of QMC5883L:
    # files: [esphome-water-meter.yaml, hmc5883l.yaml]
    refresh: 0s
```

**Comment by gmow1** [comment]
Sorry, not sure how to post but bold letters proceed with #

**Comment by tronikos** [comment]
Are you sure your have HMC and not the most common QMC? Both of them I think say HMC on the board. Try removing the hmc5883l.yaml from your config. Also add the following to see if it might be using a different address. In the logs it should print any devices found in the i2c bus.

```yaml
i2c:
  - id: !extend ${prefix_id}i2c_bus
    scan: true
```

And make sure you have wired it correctly and that you are actually using the 4 and 5 pins of your board.
